# Generated by Django 5.1.5 on 2025-09-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderitem_tshirt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment_token",
            new_name="razorpay_order_id",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="transaction_id",
            new_name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="auth_code",
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("razorpay", "Razorpay"),
                    ("card", "Credit/Debit Card"),
                    ("upi", "UPI"),
                    ("netbanking", "Net Banking"),
                    ("wallet", "Wallet"),
                ],
                default="razorpay",
                max_length=50,
            ),
        ),
    ]
