# Generated by Django 5.1.5 on 2025-09-26 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tshirt",
            name="back_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Back length from shoulder",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="condition_confidence",
            field=models.CharField(
                choices=[
                    ("certain", "Very Confident"),
                    ("mostly_certain", "Mostly Confident"),
                    ("unsure", "Somewhat Unsure"),
                    ("guessing", "Best Guess"),
                ],
                default="certain",
                help_text="How confident are you in this condition assessment?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="condition_notes",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of condition, flaws, repairs, etc.",
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="condition_photo_1",
            field=models.ImageField(
                blank=True,
                help_text="Close-up of any flaws/damage",
                null=True,
                upload_to="tshirts/condition/",
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="condition_photo_2",
            field=models.ImageField(
                blank=True,
                help_text="Care tag/label",
                null=True,
                upload_to="tshirts/condition/",
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="condition_photo_3",
            field=models.ImageField(
                blank=True,
                help_text="Material/fabric close-up",
                null=True,
                upload_to="tshirts/condition/",
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="condition_photo_4",
            field=models.ImageField(
                blank=True,
                help_text="Additional detail photo",
                null=True,
                upload_to="tshirts/condition/",
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="condition_verified",
            field=models.BooleanField(
                default=False, help_text="Has this condition been verified by staff?"
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="condition_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="condition_verifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_conditions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="front_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Front length from shoulder",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="has_fading",
            field=models.BooleanField(
                default=False, help_text="Color fading or discoloration"
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="has_holes",
            field=models.BooleanField(default=False, help_text="Any holes or tears"),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="has_pilling",
            field=models.BooleanField(
                default=False, help_text="Fabric pilling or wear"
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="has_repairs",
            field=models.BooleanField(
                default=False, help_text="Any repairs or alterations"
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="has_stains",
            field=models.BooleanField(default=False, help_text="Any visible stains"),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="pit_to_pit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Chest width (pit to pit)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="shoulder_to_shoulder",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Shoulder width",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="sleeve_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sleeve length",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tshirt",
            name="weight_grams",
            field=models.PositiveIntegerField(
                blank=True, help_text="Item weight in grams", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tshirt",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new_with_tags", "New with Tags - Brand new, never worn"),
                    (
                        "new_without_tags",
                        "New without Tags - New, never worn but tags removed",
                    ),
                    ("excellent", "Excellent - Like new, minimal signs of wear"),
                    ("very_good", "Very Good - Light wear, well-maintained"),
                    ("good", "Good - Moderate wear, still in good shape"),
                    ("fair", "Fair - Visible wear but functional"),
                    ("poor", "Poor - Heavy wear, for parts or repair only"),
                ],
                max_length=20,
            ),
        ),
    ]
