# Generated by Django 5.1.5 on 2025-09-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_enhanced_condition_reporting"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingCalculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Standard, Express, Overnight",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "estimated_days",
                    models.PositiveIntegerField(help_text="Estimated delivery days"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cost_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Cost multiplier for this method",
                        max_digits=4,
                    ),
                ),
                (
                    "max_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum weight in kg",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "max_dimensions_sum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Max sum of L+W+H in cm",
                        max_digits=6,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["estimated_days", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Local, Regional, National",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "postal_codes",
                    models.TextField(
                        blank=True, help_text="Comma-separated postal codes or ranges"
                    ),
                ),
                (
                    "states",
                    models.TextField(
                        blank=True, help_text="Comma-separated state codes"
                    ),
                ),
                (
                    "countries",
                    models.CharField(
                        default="IN",
                        help_text="Comma-separated country codes",
                        max_length=200,
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Base shipping cost for this zone",
                        max_digits=8,
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Order value threshold for free shipping",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum weight for this rate",
                        max_digits=6,
                    ),
                ),
                (
                    "max_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum weight for this rate (null = unlimited)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base cost for this weight range",
                        max_digits=8,
                    ),
                ),
                (
                    "per_kg_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional cost per kg over minimum",
                        max_digits=6,
                    ),
                ),
                (
                    "insurance_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Insurance rate as percentage (e.g., 0.02 = 2%)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="products.shippingmethod",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="products.shippingzone",
                    ),
                ),
            ],
            options={
                "ordering": ["zone", "method", "min_weight_kg"],
                "unique_together": {("zone", "method", "min_weight_kg")},
            },
        ),
        migrations.AddConstraint(
            model_name="shippingrate",
            constraint=models.CheckConstraint(
                check=models.Q(min_weight_kg__gte=0),
                name="shippingrate_min_weight_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingrate",
            constraint=models.CheckConstraint(
                check=models.Q(max_weight_kg__isnull=True)
                | models.Q(max_weight_kg__gte=models.F("min_weight_kg")),
                name="shippingrate_max_weight_gte_min",
            ),
        ),
    ]
