# Generated by Django 5.1.5 on 2025-09-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_shippingzone_countries_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shippingrate",
            name="shippingrate_min_weight_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="shippingrate",
            name="shippingrate_max_weight_gte_min",
        ),
    ]
